# Config file

DEVICE_NAME = 'SIGMACHIP'
DEVICE_CONNECTION_TIMEOUT = 1
CONNECTION_WAIT_PERIOD = 1
USER_ID = 1000
GROUP_ID = 1000
PORT = 8889
SOUND_ACTION_WEIGHT = 1
VIDEO_ACTION_WEIGHT = 3
SHUTDOWN_ACTION_WEIGHT = 0
DEBUG = True
USE_PLAYSOUND = False
BAD_BROWSER = False
IP_ADDRESSES = ['192.168.0.105']
